apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-server
  template:
    metadata:
      labels:
        app: plugin-server
    spec:
      containers:
      - name: plugin-server
        image: eliyamlevy/plugin-server:v0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: plugin-server
  labels:
    app: plugin-server
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: plugin-server
