{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "plugin-server.fullname" . }}
  namespace: {{ include "plugin-server.namespace" . }}
  labels:
{{ include "plugin-server.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
